language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support    
    - android-21
    - sys-img-armeabi-v7a-android-21
os:
  - linux
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ce63b0ed77e8bf5dc74
    on_success: change
    on_failure: always
    on_start: false
  email:
    on_success: change
    on_failure: always
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -gpu on &
  - android-wait-for-emulator
